#AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"factorial": "04_recursion.ipynb",
         "draw_line": "04_recursion.ipynb",
         "draw_interval": "04_recursion.ipynb",
         "draw_ruler": "04_recursion.ipynb",
         "binary_search": "04_recursion.ipynb",
         "disk_usage": "04_recursion.ipynb"}

modules = ["recursion.py"]

git_url = "https://github.com/owejow/python_algorithms_nbs/tree/master/"

def custom_doc_links(name): return None